# -*- coding: utf-8 -*-
"""FireDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JyxCMiZ2Q44BEo3lHYcvvw_azsMF8EbR

# Biclase con Transfer Learning
"""

# =====================================================================
# PLANTILLA GENÉRICA: Clasificación Biclase con Imágenes de Google Drive
# =====================================================================

# ---------------------------------------------------------------------
# PASO 1: Conectar a Google Drive
# ---------------------------------------------------------------------
from google.colab import drive
drive.mount('/content/drive')

# ---------------------------------------------------------------------
# PASO 2: Importar Librerías Universales
# ---------------------------------------------------------------------
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# Configuración automática de Hardware (GPU si está activa, si no CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Trabajando con el dispositivo: {device}\n")

# ---------------------------------------------------------------------
# PASO 3: Configurar Rutas del Dataset (¡MODIFICA AQUÍ!)
# ---------------------------------------------------------------------
# Si tu carpeta principal en Drive se llama diferente a "CNN", cambia el nombre aquí.
RUTA_TRAIN = '/content/drive/MyDrive/CNN/TRAIN/'
RUTA_TEST = '/content/drive/MyDrive/CNN/TEST/'

# ---------------------------------------------------------------------
# PASO 4: Transformaciones de Imágenes (Data Augmentation)
# ---------------------------------------------------------------------
# Nota didáctica: ResNet, VGG y la mayoría de redes comerciales esperan 224x224.
# Si tus imágenes son muy grandes o muy chicas, aquí controlas su entrada a la red.
transformaciones_train = transforms.Compose([
    transforms.Resize((224, 224)),           # Redimensionar todas las imágenes al mismo tamaño
    transforms.RandomHorizontalFlip(),       # Volteo aleatorio (Data Augmentation opcional)
    transforms.ToTensor(),                   # Convertir a Tensor de PyTorch en rango [0, 1]
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]) # Normalización estándar de ImageNet
])

transformaciones_test = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# ---------------------------------------------------------------------
# PASO 5: Carga Automática de Datos (ImageFolder)
# ---------------------------------------------------------------------
# ImageFolder mapea automáticamente el nombre de las subcarpetas como las etiquetas.
# Ejemplo: si ve "perros" y "gatos", a perros le asignará 0 y a gatos 1 de forma alfabética.
train_dataset = ImageFolder(root=RUTA_TRAIN, transform=transformaciones_train)
test_dataset = ImageFolder(root=RUTA_TEST, transform=transformaciones_test)

# DataLoaders: Agrupan los datos en lotes (batches)
BATCH_SIZE = 32 # Puedes bajarlo a 16 si te da error de memoria (Out of Memory)
train_loader = DataLoader(dataset=train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Imprimir las clases detectadas para verificar que todo esté en orden
clases = train_dataset.classes
print(f"Clases detectadas en Drive de forma alfabética: {clases}")
print(f"Mapeo de etiquetas: {train_dataset.class_to_idx}")
print(f"Total de imágenes de entrenamiento: {len(train_dataset)}")
print(f"Total de imágenes de prueba: {len(test_dataset)}\n")

# ---------------------------------------------------------------------
# PASO 6: Arquitectura de la Red Convolucional (Modificable)
# ---------------------------------------------------------------------
# CAMBIO PARA USAR TRANSFER LEARNING:
import torchvision.models as models

# 1. Cargamos una estructura ya existente con pesos preentrenados en ImageNet
pesos = models.ResNet18_Weights.DEFAULT
model = models.resnet18(weights=pesos)

# 2. CONGELAMOS las capas base para aprovechar su conocimiento (no se entrenarán)
for param in model.parameters():
    param.requires_grad = False

# 3. REEMPLAZAMOS únicamente la última capa (la cabeza de clasificación)
# Conservamos sus características de entrada (512) y le decimos que la salida ahora es 2 (biclase)
num_caracteristicas = model.fc.in_features
model.fc = nn.Linear(num_caracteristicas, 2)

# 4. Lo enviamos al hardware
model = model.to(device)

# ---------------------------------------------------------------------
# PASO 7: Función de Pérdida y Optimidad
# ---------------------------------------------------------------------
criterion = nn.CrossEntropyLoss() # Ideal para clasificación
optimizer = optim.Adam(model.parameters(), lr=0.001) # Ritmo de aprendizaje (Learning Rate)

# ---------------------------------------------------------------------
# PASO 8: Bucle de Entrenamiento (Training Loop)
# ---------------------------------------------------------------------
NUM_EPOCHS = 5 # Modifica el número de épocas según requieras más entrenamiento
print("Iniciando el entrenamiento de la red...")

for epoch in range(NUM_EPOCHS):
    model.train()
    loss_acumulada = 0.0

    for imagenes, etiquetas in train_loader:
        # Mover datos al hardware seleccionado
        imagenes, etiquetas = imagenes.to(device), etiquetas.to(device)

        # Forward pass
        predicciones = model(imagenes)
        loss = criterion(predicciones, etiquetas)

        # Backward pass y optimización
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        loss_acumulada += loss.item()

    print(f"Época [{epoch+1}/{NUM_EPOCHS}] - Pérdida Promedio: {loss_acumulada/len(train_loader):.4f}")

print("¡Entrenamiento concluido!\n")

# ---------------------------------------------------------------------
# PASO 9: Evaluación Final en el Set de Prueba (Test)
# ---------------------------------------------------------------------
model.eval()
correctos = 0
total_imagenes = 0

# Desactivamos el cálculo de gradientes para ir más rápido y ahorrar memoria
with torch.no_grad():
    for imagenes, etiquetas in test_loader:
        imagenes, etiquetas = imagenes.to(device), etiquetas.to(device)
        outputs = model(imagenes)
        _, predicciones_indices = torch.max(outputs.data, 1)

        total_imagenes += etiquetas.size(0)
        correctos += (predicciones_indices == etiquetas).sum().item()

accuracy = 100 * correctos / total_imagenes
print(f"Exactitud (Accuracy) en el conjunto de TEST: {accuracy:.2f}%")

"""## Paso 10: Guardar el Modelo Entrenado

Antes de crear el archivo `app.py` para Streamlit, necesitamos guardar el modelo que acabamos de entrenar. Esto nos permitirá cargar el modelo pre-entrenado directamente en nuestra aplicación de Streamlit sin tener que re-entrenarlo cada vez.
"""

import torch
# Guardar el modelo en un archivo (por ejemplo, 'resnet18_biclase.pth')
# Asegúrate de que el directorio exista o crea uno.
RUTA_MODELO_GUARDADO = '/content/drive/MyDrive/CNN/resnet18_biclase.pth'
torch.save(model.state_dict(), RUTA_MODELO_GUARDADO)
print(f"Modelo guardado en: {RUTA_MODELO_GUARDADO}")

"""## Código para `app.py` (para Streamlit Cloud)

Este es el código que deberás guardar como `app.py` en tu repositorio de GitHub. Asegúrate de que el archivo del modelo guardado (`resnet18_biclase.pth`) también esté disponible en el mismo directorio (o una ruta relativa accesible) en tu repositorio.  

**Cambios importantes:**
- Se eliminan las dependencias de Google Colab (`google.colab`).
- Se añade la importación de `streamlit`.
- Se carga el modelo guardado (`resnet18_biclase.pth`).
- Se crea una interfaz de usuario simple para subir imágenes y obtener predicciones.
- Las transformaciones de las imágenes se adaptan para una única imagen de entrada.
"""

import streamlit as st
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image
import io

# --- Configuración del dispositivo (CPU para Streamlit Cloud si no hay GPU) ---
device = torch.device('cpu') # En Streamlit Cloud, es más probable que uses CPU

# --- Definición de la arquitectura del modelo (DEBE SER LA MISMA QUE SE ENTRENÓ) ---
@st.cache_resource # Cachea el modelo para que no se cargue en cada ejecución
def load_model():
    # Cargar la estructura de ResNet18
    model = models.resnet18(weights=None) # No necesitamos los pesos pre-entrenados de ImageNet aquí

    # Congelar las capas base (aunque no entrenaremos, es buena práctica mantener la misma estructura)
    for param in model.parameters():
        param.requires_grad = False

    # Reemplazar la última capa de clasificación
    num_caracteristicas = model.fc.in_features
    model.fc = nn.Linear(num_caracteristicas, 2) # 2 clases (fire, nofire)

    # Cargar los pesos entrenados
    # Asegúrate de que 'resnet18_biclase.pth' esté en el mismo directorio que app.py
    try:
        model.load_state_dict(torch.load('resnet18_biclase.pth', map_location=device))
    except FileNotFoundError:
        st.error("Error: El archivo del modelo 'resnet18_biclase.pth' no se encontró. ¡Asegúrate de subirlo a tu repositorio de GitHub!")
        st.stop()

    model.eval() # Poner el modelo en modo evaluación
    model = model.to(device)
    return model

model = load_model()

# --- Transformaciones para una sola imagen de inferencia ---
transforme_inferencia = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# --- Mapeo de clases (DEBE COINCIDIR CON EL ORDEN DE ENTRENAMIENTO) ---
clases = ['fire', 'nofire'] # Asegúrate de que esto coincida con train_dataset.classes

# --- Interfaz de Streamlit ---
st.set_page_config(page_title="Clasificador de Fuego", page_icon="🔥")

st.title("🔥 Clasificador de Fuego (Biclase)")
st.markdown("Una aplicación para detectar fuego en imágenes usando un modelo ResNet18 pre-entrenado.")

# Barra lateral
st.sidebar.header("Acerca de")
st.sidebar.markdown("Esta aplicación utiliza un modelo de redes neuronales convolucionales (CNN) basado en ResNet18 para clasificar imágenes. El modelo ha sido entrenado para distinguir entre imágenes con **fuego** y sin **fuego**.")
st.sidebar.markdown("\n\n**Cómo usar:**\n1. Sube una imagen en la sección principal.\n2. La aplicación mostrará la imagen y la predicción del modelo.\n")
st.sidebar.markdown("--- desarrollado con ❤️ y PyTorch")

st.header("Sube tu imagen aquí")
uploaded_file = st.file_uploader("Elige una imagen...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Leer la imagen subida
    image_data = uploaded_file.getvalue()
    image = Image.open(io.BytesIO(image_data)).convert("RGB")

    # Crear columnas para mostrar la imagen y la predicción
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Imagen Subida")
        st.image(image, caption='Imagen para analizar', use_column_width=True)

    # Preprocesar la imagen
    input_tensor = transforme_inferencia(image)
    input_batch = input_tensor.unsqueeze(0) # Añadir una dimensión de batch
    input_batch = input_batch.to(device)

    # Realizar la predicción
    with torch.no_grad():
        output = model(input_batch)
        probabilities = torch.softmax(output, dim=1)
        _, predicted_idx = torch.max(probabilities, 1)

    # Obtener el nombre de la clase y la confianza
    predicted_class = clases[predicted_idx.item()]
    confidence = probabilities[0][predicted_idx.item()].item() * 100

    with col2:
        st.subheader("Resultado de la Predicción")
        if predicted_class == 'fire':
            st.success(f"Predicción: **¡Fuego detectado!**")
            st.balloons()
        else:
            st.info(f"Predicción: **No se detectó fuego.**")
        st.write(f"Confianza: {confidence:.2f}%")

    st.markdown("--- ")
    st.caption("*Nota: La precisión del modelo puede variar. Usa esto como una herramienta de apoyo.*")

!pip install streamlit